<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.ostelco</groupId>
        <artifactId>ostelco-core</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>sim-administration</artifactId>
    <packaging>pom</packaging>

    <name>SIM Administration</name>
    <description>SIM Administration modules</description>

    <modules>
        <module>es2plus4dropwizard</module>
        <module>jersey-json-schema-validator</module>
        <module>hss-adapter</module>
        <module>ostelco-dropwizard-utils</module>
        <module>simcard-utils</module>
        <module>simmanager</module>
        <module>sm-dp-plus-emulator</module>
    </modules>
</project>