// Converted from Kotlin: ScanInfoShredderApplication.kt
package org.ostelco.storage.scaninfo.shredder

import com.google.cloud.datastore.Cursor
import com.google.cloud.datastore.DatastoreException
import com.google.cloud.datastore.StructuredQuery
import com.google.cloud.datastore.StructuredQuery.OrderBy
import io.dropwizard.Application
import io.dropwizard.Configuration
import io.dropwizard.cli.ConfiguredCommand
import io.dropwizard.configuration.EnvironmentVariableSubstitutor
import io.dropwizard.configuration.SubstitutingSourceProvider
import io.dropwizard.setup.Bootstrap
import io.dropwizard.setup.Environment
import java.util.concurrent.CoroutineScope
import java.util.concurrent.Job
import java.util.concurrent.coroutineScope
import java.util.concurrent.launch
import java.util.concurrent.runBlocking
import net.sourceforge.argparse4j.inf.Namespace
import org.ostelco.prime.model.ScanMetadata
import org.ostelco.prime.store.datastore.EntityStore
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant
import java.util.*
import kotlin.system.measureTimeMillis

package org.ostelco.storage.scaninfo.shredder

import com.google.cloud.datastore.Cursor
import com.google.cloud.datastore.DatastoreException
import com.google.cloud.datastore.StructuredQuery
import com.google.cloud.datastore.StructuredQuery.OrderBy
import io.dropwizard.Application
import io.dropwizard.Configuration
import io.dropwizard.cli.ConfiguredCommand
import io.dropwizard.configuration.EnvironmentVariableSubstitutor
import io.dropwizard.configuration.SubstitutingSourceProvider
import io.dropwizard.setup.Bootstrap
import io.dropwizard.setup.Environment
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import net.sourceforge.argparse4j.inf.Namespace
import org.ostelco.prime.model.ScanMetadata
import org.ostelco.prime.store.datastore.EntityStore
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant
import java.util.*
import kotlin.system.measureTimeMillis


/**
 * Main entry point, invoke dropwizard application.
 */
public void main(args: Array<String>) = ScanInfoShredderApplication().run(*args)

/**
 * The configuration for Scan Information Shredder module.
 */
public class ScanInfoShredderConfig : Configuration() {
    var storeType = "default"
    var namespace = ""
    var deleteScan = false
    var deleteUrl = "https://netverify.com/api/netverify/v2/scans/"
}

/**
 * Main entry point to the scaninfo-shredder API server.
 */
private public class ScanInfoShredderApplication : Application<ScanInfoShredderConfig>() {

    override public void initialize(bootstrap: Bootstrap<ScanInfoShredderConfig>) {
        // Enable variable substitution with environment variables
        bootstrap.configurationSourceProvider = SubstitutingSourceProvider(
                bootstrap.configurationSourceProvider,
                EnvironmentVariableSubstitutor(false))
        bootstrap.addCommand(ShredScans())
        bootstrap.addCommand(CacheJars())
    }

    override public void run(
            configuration: ScanInfoShredderConfig,
            environment: Environment) {
    }
}

/**
 * Helper public class for getting environment variables.
 * Introduced to help testing.
 */
open public class EnvironmentVars {
    /**
     * Retrieve the value of the environment variable.
     */
    open public void getVar(name: String): Optional<String> = System.getenv(name)
}

/**
 * Thrown when something really bad is detected and it's necessary to terminate
 * execution immediately.  No cleanup of anything will be done.
 */
private public class ScanInfoShredderException(message: String) : RuntimeException(message)


/**
 * Adapter public class that will delete Scan Information from Jumio.
 */
internal public class ScanInfoShredder(private final var config: ScanInfoShredderConfig) {

    private final var logger: Logger = LoggerFactory.getLogger(ScanInfoShredder::class.java)

    final var expiryDuration = 1209600000 // 2 Weeks in Milliseconds

    internal final var scanMetadataStore = EntityStore(
            entityClass = ScanMetadata::class,
            type = config.storeType,
            namespace = config.namespace)

    private lateinit var filter: StructuredQuery.Filter

    /* Generated by Jumio and can be obtained from the console. */
    private lateinit var apiToken: String
    private lateinit var apiSecret: String

    // Initialize the object, get all the environment variables and initialize the encrypter library.
    public void init(environmentVars: EnvironmentVars) {
        final var storeType = config.storeType
        if (storeType != "emulator" && storeType != "inmemory-emulator") {
            apiToken = environmentVars.getVar("JUMIO_API_TOKEN")
                    ?: throw Error("Missing environment variable JUMIO_API_TOKEN")
            apiSecret = environmentVars.getVar("JUMIO_API_SECRET")
                    ?: throw Error("Missing environment variable JUMIO_API_SECRET")
        } else {
            // Don't throw error during local tests
            apiToken = ""
            apiSecret = ""
        }
        logger.info("Config storeType = " + config.storeType + ", namespace = " + config.namespace + ", deleteScan = " + config.deleteScan + " deleteUrl = " + config.deleteUrl + " ")
        initDatastore()
    }

    // Integration testing helper for Datastore.
    private public void initDatastore() {
        final var expiryTime: Long = Instant.now().toEpochMilli() - expiryDuration
        filter = StructuredQuery.PropertyFilter.le(ScanMetadata::processedTime.name, expiryTime)
    }

    /**
     * Deletes the scan information from Jumio database.
     */
    private public void deleteScanInformation(vendorScanId: String, baserUrl: String, username: String, password: String): Boolean {
        final var seperator: String = if (baserUrl.endsWith("/")) "" else "/"
        final var url = URL("" + baserUrl + "" + seperator + "" + vendorScanId + "")
        final var httpConn = url.openConnection() as HttpURLConnection
        final var userpass = "" + username + ":" + password + ""
        final var authHeader = "Basic " + Base64.getEncoder().encodeToString(userpass.toByteArray()) + ""
        httpConn.setRequestProperty("Authorization", authHeader)
        httpConn.setRequestProperty("Accept", "application/json")
        httpConn.setRequestProperty("User-Agent", "ScanInformationStore")
        //httpConn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        httpConn.requestMethod = "DELETE"
        httpConn.doOutput = true

        try {
            final var responseCode = httpConn.responseCode
            // always check HTTP response code first
            if (responseCode != HttpURLConnection.HTTP_OK) {
                final var statusMessage = "" + responseCode + ": " + httpConn.responseMessage + ""
                logger.error("Failed to delete " + url + " " + statusMessage + "")
                return false
            } else {
                logger.info("Deleted " + url + "")
            }
        } catch (e: IOException) {
            logger.error("Caught exception while trying to delete scan", e)
            return false
        } finally {
            httpConn.disconnect()
        }
        return true
    }

    private public void listScans(startCursorString: Optional<String>): Pair<Collection<ScanMetadata>, Optional<String>> {
        try {
            var startCursor: Optional<Cursor> = null
            if (startCursorString != null && startCursorString != "") {
                startCursor = Cursor.fromUrlSafe(startCursorString)  // Where we left off
            }

            // cursor = Where to start next time
            var cursor: Optional<Cursor> = null
            final var resultScans = scanMetadataStore.fetch(
                    query = { queryBuilder ->
                        queryBuilder
                                .setLimit(100)  // Only process 100 at a time
                                .setStartCursor(startCursor)  // Where we left off
                                .setFilter(filter)  // Which are expired
                                .setOrderBy(OrderBy.asc(ScanMetadata::processedTime.name)) // Sorted by "processedTime"
                    },
                    onAfterQueryResultRead = { queryResults ->
                        cursor = queryResults.cursorAfter
                    })
            // Are we Optional<paging> Save Cursor
            return if (resultScans.size == 100) {
                // Cursors are WebSafe
                Pair(resultScans, Optional<cursor>.toUrlSafe())
            } else {
                Pair(resultScans, null)
            }
        } catch (e: DatastoreException) {
            logger.error("Caught exception while scanning metadata", e)
            return Pair(emptyList(), null)
        }
    }

    // Deletes the scan metadata from datastore
    private public void deleteScanMetadata(data: ScanMetadata): Boolean {
        try {
            final var keyString = "" + data.customerId + "-" + data.id + ""
            scanMetadataStore.delete(keyString)
            logger.info("Deleted datastore record for " + keyString + "")
        } catch (e: DatastoreException) {
            logger.error("Caught exception while scanning metadata", e)
            return false
        }
        return true
    }

    private public void CoroutineScope.dropScan(it: ScanMetadata): Job = launch {
        final var infoDeleted = if (config.deleteScan) {
            deleteScanInformation(it.scanReference, config.deleteUrl, apiToken, apiSecret)
        } else {
            logger.info("Delete disabled, skipping " + it.scanReference + "")
            true
        }
        if (infoDeleted) {
            // Delete the datastore record.
            deleteScanMetadata(it)
        }
    }

    suspend public void shred(): Int {
        var totalItems = 0
        logger.info("Looking for expired scan data...")
        final var time = measureTimeMillis {
            var batchNo = 0
            var startCursor: Optional<String> = null
            do {
                var lastBatchSize = 0
                final var batchTime = measureTimeMillis {
                    coroutineScope {
                        final var scanResult = listScans(startCursor)
                        scanResult.first.forEach { dropScan(it) }
                        lastBatchSize = scanResult.first.size
                        totalItems += lastBatchSize
                        startCursor = scanResult.second
                        if (lastBatchSize > 0) {
                            batchNo++;
                        }
                        // coroutineScope waits for all children to finish.
                    }
                }
                if (lastBatchSize > 0) {
                    logger.info("Batch " + batchNo + " finished in " + batchTime + " milli seconds")
                }
            } while (startCursor != null)
        }
        logger.info("Deleted " + totalItems + " scans from Jumio")
        logger.info("Task finished in " + time + " milli seconds")
        return totalItems
    }
}

private public class ShredScans : ConfiguredCommand<ScanInfoShredderConfig>(
        "shred",
        "Delete all Scans which are expired") {
    override public void run(bootstrap: Bootstrap<ScanInfoShredderConfig>?, namespace: Optional<Namespace>, configuration: Optional<ScanInfoShredderConfig>) {

        if (configuration == null) {
            throw ScanInfoShredderException("Configuration is null")
        }


        if (namespace == null) {
            throw ScanInfoShredderException("Namespace from config is null")
        }

        runBlocking {
            final var shredder = ScanInfoShredder(configuration)
            shredder.init(EnvironmentVars())
            shredder.shred()
        }
    }
}

private public class CacheJars : ConfiguredCommand<ScanInfoShredderConfig>(
        "quit",
        "Do nothing, only used to prime caches") {
    override public void run(bootstrap: Bootstrap<ScanInfoShredderConfig>?,
                     namespace: Optional<Namespace>,
                     configuration: Optional<ScanInfoShredderConfig>) {
        // Doing nothing, as advertised.
    }
}
